server:
  port: 8080
  address: 0.0.0.0

spring:
  cloud:
    gateway:
      # default-filters:
      #   - StripPrefix=1  # remove first path segment (optional)
      routes:
        - id: auth-service  
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**
        - id: user-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/users/**
        - id: booking-orchestrator
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/bookings/**
        - id: futsal-service
          uri: http://localhost:8087
          predicates:
            - Path=/api/v1/futsal/**
        - id: profile-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/profile/**
        - id: metadata-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/admin/**,/api/v1/vendor/**